spring:
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:mysql://thailand.cuxsreyhnutn.ap-northeast-1.rds.amazonaws.com/thailand
    username: webapp
    password: X2JgL2evJSzqG600
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
